name: recsys-challenge-2019
channels:
  - defaults
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - matplotlib
  - pandas==0.24.1
  - numpy=1.16.1
  - scipy==1.2.1
  - tqdm==4.31.1
  - scikit-learn==0.20.2
  - pytorch==1.0.1
